apiVersion: v1
kind: Service
metadata:
  name: ad-service
  labels:
    app: ad-service
spec:
  type: LoadBalancer
  selector:
    app: parking-adv-node
  ports:
    - port: 5200
      protocol: TCP
      targetPort: 5000